name: Go CI Pipeline
on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  golanci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version-file: 'go.mod'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.3
    
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      
      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: '**/go.sum'
          
      - name: Verify dependencies
        run: go mod verify
        
      - name: Run tests with race detector
        run: go test -race -coverprofile=coverage.out ./...
        
      - name: Upload coverage
        uses: actions/upload-artifact@v7
        with:
          name: coverage-report
          path: coverage.out
