# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

permissions:
  contents: write   # tags, releases, reintegration push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  run-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pipery-dev/pipery-golang-ci@v1
        with:
          project_path: .
          config_file: .pipery/config.yaml
          go_version: 1.22
          skip_sast: false
          skip_sca: false
          skip_lint: false
          skip_build: false
          tests_path: ./...
          target_platforms:  linux/amd64,linux/arm64,linux/arm
          skip_test: false
          skip_versioning:     ${{ github.event_name == 'pull_request' }}
          skip_release:        ${{ github.event_name == 'pull_request' }}
          skip_reintegration:  ${{ github.event_name == 'pull_request' }}
          skip_packaging: true
          version_bump: patch
          github_token: ${{ secrets.GITHUB_TOKEN }}
          log_file: pipery.jsonl
